### ISSUE TITLE
Support for `unifiedRoleAssignment` for different RBAC providers

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-bicep-types#123]
**Is your feature request related to a problem? Please describe.**
I'm trying to add a new resource `unifiedRoleAssignment`, but there are several issues.

1. Resource is under more URIs
The resource `unifiedRoleAssignment `represents a role assignment, but the type is returned by more RBAC providers.
All these endpoints return `unifiedRoleAssignment`:
`/roleManagement/directory/roleAssignments`
`/roleManagement/entitlementManagement/roleAssignments`
`/roleManagement/exchange/roleAssignments` - beta only

Now, it's possible to specify only one `RootUri`. 

```
  - Name: microsoft.graph.unifiedRoleAssignment
    RootUri: /roleManagement/directory/roleAssignments
    AvailableProperty:
      - appScopeId
      - directoryScopeId
      - principalId
      - roleDefinitionId
    RequiredOnWrite:
      - appScopeId
      - directoryScopeId
      - principalId
      - roleDefinitionId
```
3. Wrong path generated
Generated path for 

```
  - Name: microsoft.graph.unifiedRoleAssignment
    RootUri: /roleManagement/directory/roleAssignments
    AvailableProperty:
      - appScopeId
      - directoryScopeId
      - principalId
      - roleDefinitionId
    RequiredOnWrite:
      - appScopeId
      - directoryScopeId
      - principalId
      - roleDefinitionId
```
Generated path is `/{rootScope}/providers/Microsoft.Graph/directory/{directoryId}/roleAssignments/{unifiedRoleAssignmentId}` which seems to me wrong. It should be `/{rootScope}/providers/Microsoft.Graph/roleManagement/directory/roleAssignments/{unifiedRoleAssignmentId}`/

**Describe the solution you'd like**
Maybe add new property `EntityType`. Config.yml can contain the same EntityType but with different combination of Name and RootUri
```
  - Name: microsoft.graph.entraRoleAssignment
    EntityType: microsoft.graph.unifiedRoleAssignment
    RootUri: /roleManagement/directory/roleAssignments
  - Name: microsoft.graph.exchangeRoleAssignment
    EntityType: microsoft.graph.unifiedRoleAssignment
    RootUri: /roleManagement/exchange/roleAssignments
```

**Additional context**
